# -*- coding: utf-8 -*-
"""moviesRecommendationSystemApp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WswHY_fJnnJYncK1RMgZJb6LadgZlWe4
"""

import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

filePath = "/content/drive/MyDrive/MRS/cleaned_movies.csv"

df = pd.read_csv(filePath)
print("="*50)
print("IMDb Movie Recommendation System")
print("="*50)

# Converting runtime to numeric
df["Runtime_Minutes"] = df["Runtime"].str.extract(r'(\d+)').astype(float)

# Extract and sort unique genres
all_genres = df['Genre'].str.split(', ').explode().unique()
all_genres = sorted([g.strip() for g in all_genres if g.strip()])
genre_map = {str(i + 1): g for i, g in enumerate(all_genres)}

while True:
    print("\n--- Movie Recommendation Menu ---")

    # Genre Selection
    print("\nAvailable Genres:")
    for i, g in enumerate(all_genres):
        print(f"{i+1}. {g}")

    genreInput = input(f"Enter a number for Genre (1-{len(all_genres)}): ").strip()
    try:
        selected_genre = genre_map.get(genreInput)
        if not selected_genre:
            raise ValueError("Invalid genre selection.")
    except ValueError as e:
        print(f"Error: {e}. Please enter a valid number for the genre.")
        continue # Restart loop for valid input

    # Minimum IMDb Rating
    try:
        min_rating = float(input("Minimum IMDb Rating (0-10): ").strip())
        if not (0 <= min_rating <= 10):
            raise ValueError("Rating must be between 0 and 10.")
    except ValueError as e:
        print(f"Error: {e}. Please enter a valid number for minimum rating.")
        continue # Restart loop

    # Maximum Runtime
    try:
        max_runtime = int(input("Maximum Runtime (minutes): ").strip())
        if max_runtime <= 0:
            raise ValueError("Runtime must be a positive number.")
    except ValueError as e:
        print(f"Error: {e}. Please enter a valid integer for maximum runtime.")
        continue # Restart loop

    # Filter by movies
    recommended = df[
                  (df["Genre"].str.contains(selected_genre, case=False)) &
                  (df["IMDB_Rating"] >= min_rating) &
                  (df["Runtime_Minutes"] <= max_runtime)
                ]

    # Sort by rating
    recommended = recommended.sort_values(by="IMDB_Rating", ascending=False)

    print(f"\nRecommended Movies for Genre: {selected_genre}, Min Rating: {min_rating}, Max Runtime: {max_runtime} minutes\n")

    if len(recommended) == 0:
      print("Not much movies found with the given criteria.")
    else:
        for i, row in recommended.head(10).iterrows():
          print("************************")
          print("Title: ", row["Series_Title"])
          print("Genre: ", row["Genre"])
          print("IMDB Rating: ", row["IMDB_Rating"])
          print("Runtime: ", row["Runtime"])
          print("Director: ", row["Director"])
          print("************************")

    play_again = input("\nDo you want to find more movies? (yes/no): ").strip().lower()
    if play_again != 'yes':
        print("Thank you for using the IMDb Movie Recommendation System!")
        break

import matplotlib.pyplot as plt
import seaborn as sns

# Visualize the distribution of IMDB ratings
fig, ax = plt.subplots(figsize=(10, 6))
sns.histplot(df['IMDB_Rating'], bins=10, kde=True, ax=ax)
ax.set_title('Distribution of IMDB Ratings')
ax.set_xlabel('IMDB Rating')
ax.set_ylabel('Number of Movies')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Prepare data for box plot by handling multiple genres
df_genres = df.assign(Genre=df['Genre'].str.split(', ')).explode('Genre')

# Create a box plot to compare IMDB ratings across different genres
plt.figure(figsize=(15, 8))
sns.boxplot(x='Genre', y='IMDB_Rating', data=df_genres.sort_values('IMDB_Rating', ascending=False))
plt.title('IMDb Ratings Distribution Across Genres')
plt.xlabel('Genre')
plt.ylabel('IMDb Rating')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# Export the recommended movies to a new CSV file
output_file_path = "/content/drive/MyDrive/MRS/recommended_movies.csv"
recommended.to_csv(output_file_path, index=False)
print(f"Recommended movies exported successfully to {output_file_path}")

